Update CMakeLists.txt
OpenVisualCloud/Media-Communications-Mesh pull request #155
Opened 2024-06-28 13:12 UTC by tszumski

Update CMakeLists.txt append "-fPIC" flag

2024-07-01 05:59 UTC, Mionsz requested changes
Could you add the same C  flags for the `memif` library, as it is also build as dynamically linked library. Probably in:
`sdk/3rdparty/libmemif/src/CMakeLists.txt`

2024-07-01 06:14 UTC, tszumski commented
> Could you add the same C flags for the `memif` library, as it is also build as dynamically linked library. Probably in: `sdk/3rdparty/libmemif/src/CMakeLists.txt`

Done

2024-07-01 19:26 UTC, Mionsz approved these changes

2024-07-02 14:26 UTC, MateuszGrabuszynski approved these changes
lgtm

2024-07-02 14:29 UTC, Mionsz commented
@pwysock1-intel @soopel can you check this one and approve if it is ok so that we don't stall?

2024-07-02 14:34 UTC, soopel approved these changes
Approved

2024-07-02 14:38 UTC, merged