Run basic implementation of AF_XDP/eBPF
OpenVisualCloud/Media-Communications-Mesh pull request #180
Opened 2024-08-26 06:46 UTC by Mionsz

Run basic implementation of AF_XDP/eBPF using mtl native functions and MtlManager. The enablement of `native_af_xdp` for interfaces used in media-proxy workloads required minor impact changes in Dockerfile build sequence as well as adjustments to proxy_context.cc

Biggest issue was encountered for number of queues that are predefined and hardcoded in media-proxy. Current approach treats ax_xdp as alternative case and uses value `62` instead of `128`  for `rx_queues_cnt` and `tx_queues_cnt`.

Test scripts are partially developed and currently not enabled. After confirmed one node deployment possibility I will adjust and enable them.

2024-08-28 14:38 UTC, soopel approved these changes
Looks good to me.

2024-08-28 14:52 UTC, ko80 commented on media-proxy/README.md
> +> `MtlManager`, from Media-Transport-Library `manager` subdirectory, must be running
```suggestion
> `MtlManager`, from Media-Transport-Library `manager` subdirectory, must be running.
```

2024-08-28 14:53 UTC, ko80 commented on media-proxy/README.md
> +> Only device physical function with preconfigured IP address can be used for `native_af_xdp` mode.
```suggestion
> Only a device physical function with a preconfigured IP address can be used for the `native_af_xdp` mode.
```

2024-08-28 14:59 UTC, ko80 requested changes
Please add more details on how to configure devices for AF_XDP/eBPF on a single node with an E810 NIC card and setup all environment for that. Provide an example of configuring Tx and Rx sides when sending data in that mode.

2024-08-28 15:01 UTC, ko80 commented on tests/single-node-sample-apps/README.md
> +   * `af_xdp` - use native_af_xdp connection for media proxy. MtlManager required.
```suggestion
   * `af_xdp` - use a native_af_xdp connection for media proxy. MtlManager is required to be running.
```

2024-08-28 15:05 UTC, ko80 commented
Could you elaborate more on why exactly `62` queues are used, not `128`? Lack of resources? Why not `64`?

2024-08-29 08:23 UTC, Mionsz commented
@ko80 There are 64 queues hardcoded in the MTL but the first one is reserved for system usage. Still when I set it to 63 it does not work (something in logic may be wrong), the 62 is the first number working

2024-09-11 11:48 UTC, ko80 commented on media-proxy/README.md
> +Notice that device must have a preassigned IP address and `--ip` parameter will not work.
```suggestion
Notice that the device must have a pre-assigned IP address. The `--ip` parameter is not applied in this mode.
```

2024-09-11 11:48 UTC, ko80 commented on media-proxy/README.md
> +> Only a device physical function with a preconfigured IP address can be used for the `native_af_xdp` mode.
```suggestion
> Only a device physical function with a pre-configured IP address can be used for the `native_af_xdp` mode.
```

2024-09-11 11:52 UTC, ko80 approved these changes
LGTM

2024-09-11 12:05 UTC, merged