Rewrite test app
OpenVisualCloud/Media-Communications-Mesh pull request #284
Opened 2024-12-04 18:14 UTC by zLukas

2024-12-05 11:25 UTC, marcin-le requested changes
application should go to tests/tools

2024-12-05 15:09 UTC, zLukas commented
> application should go to tests/tools

done

2024-12-06 10:32 UTC, MateuszGrabuszynski commented
Wait a minute, we need to have ONLY changes made specifically for this PR in the PR, without the jiggle-juggle of the other stuff. I rebased val-dev to main, could you please rebase your fork's branch to val-dev? Thanks. :)

2024-12-09 15:24 UTC, MateuszGrabuszynski commented
The rebase removed the copyright header changes, but should we consider changes from `.github/workflows` as a part of this PR?

2024-12-10 10:25 UTC, zLukas commented
> The rebase removed the copyright header changes, but should we consider changes from `.github/workflows` as a part of this PR?

unnecessary changes cleaned up

2024-12-10 15:10 UTC, KarolinaPomian commented on tests/tools/TestApp/README.md
> +#TestApp
```suggestion
# TestApp
```

2024-12-10 16:45 UTC, zLukas commented on tests/tools/TestApp/README.md
> +#TestApp
done

2024-12-11 11:56 UTC, MateuszGrabuszynski approved these changes
LGTM 👍🏻

2024-12-12 08:47 UTC, merged